2020/03/16 16:22:06 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: docker-test.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "docker-test.com:8080", referrer: "http://docker-test.com:8080/"
2020/03/16 16:22:08 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: docker-test.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "docker-test.com:8080", referrer: "http://docker-test.com:8080/index.html"
2020/03/16 16:22:18 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: docker-test.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "docker-test.com:8080", referrer: "http://docker-test.com:8080/index.html"
